In [157]:
# dealing with NumPy package
import numpy as np

In [158]:
data1 = [1, 2, 3, 4, 5]      # creating a list
arr1 = np.array(data1)       # creating 1d array from list

In [159]:
data1

[1, 2, 3, 4, 5]

In [160]:
arr1

array([1, 2, 3, 4, 5])

In [161]:
data2 = [range(1,5),range(5,9)]         # creating list of lists

In [162]:
data2

[range(1, 5), range(5, 9)]

In [163]:
arr2 = np.array(data2)

In [164]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [165]:
arr2.tolist()                 # converting array to list

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [166]:
# examining arrays
arr1.dtype

dtype('int32')

In [167]:
arr2.dtype

dtype('int32')

In [168]:
arr2.ndim

2

In [169]:
arr2.size

8

In [170]:
len(arr2)

2

In [171]:
# create special arrays
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [172]:
np.zeros((3,6),int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [173]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [174]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [175]:
np.diag([11,22,44,55,33])

array([[11,  0,  0,  0,  0],
       [ 0, 22,  0,  0,  0],
       [ 0,  0, 44,  0,  0],
       [ 0,  0,  0, 55,  0],
       [ 0,  0,  0,  0, 33]])

In [176]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [177]:
np.logspace(0,3,4)

array([   1.,   10.,  100., 1000.])

In [178]:
np.logspace(0,3,4,base=2)

array([1., 2., 4., 8.])

In [179]:
# arange is like range, except it returns an array not a list
int_array = np.arange(5)
float_array = int_array.astype(float)

In [180]:
float_array

array([0., 1., 2., 3., 4.])

In [181]:
int_array

array([0, 1, 2, 3, 4])

In [182]:
# reshaping
matrix = np.arange(10,dtype=float)
matrix

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [183]:
matrix.shape

(10,)

In [184]:
matrix = matrix.reshape(5,2)

In [185]:
matrix

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [186]:
matrix.shape

(5, 2)

In [187]:
matrix.T

array([[0., 2., 4., 6., 8.],
       [1., 3., 5., 7., 9.]])

In [188]:
# slicing operations
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [189]:
arr2[0,:]

array([1, 2, 3, 4])

In [190]:
arr2[:,0]

array([1, 5])

In [191]:
arr2[:,:2]

array([[1, 2],
       [5, 6]])

In [192]:
arr2[:,2:]

array([[3, 4],
       [7, 8]])

In [193]:
# creating views and copies
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [194]:
arr[5:8] = 200
arr

array([  0,   1,   2,   3,   4, 200, 200, 200,   8,   9])

In [195]:
arr_view = arr[5:8]
arr_view

array([200, 200, 200])

In [232]:
arr_view[1] = 500
arr_view

array([100, 500, 100])

In [233]:
arr

array([  0,   1,   2,   3,   4, 100, 500, 100, 100, 100])

In [196]:
arr_copy = arr[5:8].copy()
arr_copy

array([200, 200, 200])

In [235]:
arr_copy[1] = 1000
arr_copy

array([ 200, 1000,  200])

In [236]:
arr

array([  0,   1,   2,   3,   4, 100, 500, 100, 100, 100])

In [198]:
arr[arr > 5]

array([200, 200, 200,   8,   9])

In [199]:
arr[arr > 5] = 100
arr

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100])

In [200]:
names = np.array(["bob","joe","will","bob"])
names == "bob"

array([ True, False, False,  True])

In [201]:
names [(names != "bob") | (names == "will")]

array(['joe', 'will'], dtype='<U4')

In [202]:
names [names != "bob"] = "joe"

In [203]:
names

array(['bob', 'joe', 'joe', 'bob'], dtype='<U4')

In [204]:
np.unique(names)

array(['bob', 'joe'], dtype='<U4')

In [205]:
nums = np.arange(5)
nums

array([0, 1, 2, 3, 4])

In [206]:
nums * 10

array([ 0, 10, 20, 30, 40])

In [ ]:
#nums = np.sqrt(nums)
nums = np.arange(5)
nums

In [ ]:
nums = np.sqrt(nums)
nums

In [208]:
np.ceil(nums)

array([0., 1., 2., 2., 2.])

In [209]:
np.isnan(nums)

array([False, False, False, False, False])

In [210]:
nums = np.arange(5)
print(nums)
nums = nums + np.arange(5)
nums

[0 1 2 3 4]


array([0, 2, 4, 6, 8])

In [ ]:
# vector operations 
vect1 = np.random.randn(10)
print (vect1)
vect2 = np.random.rand(10)
print (vect2)
vect_int =vect1.copy().astype(int)
print(vect_int)
dist = np.sqrt(np.sum((vect1-vect2)**2))# calculating Euclidian distance

In [ ]:
dist

In [213]:
vect1

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

In [214]:
vect2

array([0.68346294, 0.71270203, 0.37025075, 0.56119619, 0.50308317,
       0.01376845, 0.77282662, 0.88264119, 0.36488598, 0.61539618])

In [215]:
vect2

array([0.68346294, 0.71270203, 0.37025075, 0.56119619, 0.50308317,
       0.01376845, 0.77282662, 0.88264119, 0.36488598, 0.61539618])

In [216]:
rnd = np.random.randn(4,2)
rnd

array([[-0.20264632, -0.65596934],
       [ 0.19342138,  0.55343891],
       [ 1.31815155, -0.46930528],
       [ 0.67555409, -1.81702723]])

In [217]:
# dealing with statistics and mathematical functions...

In [218]:
rnd.mean()


-0.05054778166682432

In [219]:
rnd.std()                            # calculating standard deviations

0.9021058265703192

In [220]:
rnd.min()

-1.8170272265901968

In [221]:
rnd.max()

1.3181515541801367

In [240]:
print (rnd)
rnd.sum(axis=0)

[[-0.20264632 -0.65596934]
 [ 0.19342138  0.55343891]
 [ 1.31815155 -0.46930528]
 [ 0.67555409 -1.81702723]]


array([ 1.98448069, -2.38886294])

In [241]:
print (rnd)
rnd.sum(axis=1)

[[-0.20264632 -0.65596934]
 [ 0.19342138  0.55343891]
 [ 1.31815155 -0.46930528]
 [ 0.67555409 -1.81702723]]


array([-0.85861567,  0.74686029,  0.84884627, -1.14147314])

In [224]:
(rnd>0).sum()                      # counting the number of +ve numbers

4

In [225]:
(rnd>0).any()

True

In [226]:
(rnd>0).all()

False

In [227]:
num= np.arange(32).reshape(8,4)
num

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [228]:
num.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [229]:
num.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [230]:
np.random.seed(1234)

In [231]:
# broadcasting
a = np.array([[0,0,0],
             [10,10,10],
             [20,20,20],
             [30,30,30]])
b = np.array([0,1,2])
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])